[package]
name = "advent-of-code"
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
itertools = "0.13.0"
nom = "7.1.3"
clap = { version = "4.5.21", features = ["derive"] }
chrono = "0.4.38"
atoi = "2.0.0"

[dev-dependencies]
rstest = "0.23.0"
